name: wildpulse_prototype_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1  # ✅ Updated version (compatible with latlong2 0.9.x)
  latlong2: ^0.9.1     # ✅ Compatible with flutter_map >= 8.0.0
  web_socket_channel: ^2.4.0
  geolocator: ^11.1.0
  path_provider: ^2.0.14
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  flutter_local_notifications: ^19.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/wild.jpg
    - assets/hog.jpg
    - assets/philippine_hornbill.jpg
    - assets/visayan_warty_pig.jpg
    - assets/wildlogo.jpg
    - assets/visayan_spotted_deer.jpg
    - assets/wildpulse.png
